version: "2"
services:
  flybitscoffee:
    build: .
    volumes:
      - ./:/app
    links:
      - mongo
    ports:
      - "3000:3000"
    environment:
      - MONGO_URL=mongodb://mongo:27017/flybitscoffee
    restart: always
  mongo:
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"